export const headers = {
    galxe: {
        authority: 'graphigo.prd.galaxy.eco',
        accept: '*/*',
        'accept-language': '',
        authorization: '',
        'content-type': 'application/json',
        origin: 'https://galxe.com',
        'request-id': '',
        'sec-ch-ua': '',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'cross-site',
        'user-agent': '',
    },
    route: {
        authority: 'artio-80085-dex-router.berachain.com',
        accept: '*/*',
        'accept-language': '',
        origin: 'https://artio.bex.berachain.com',
        referer: 'https://artio.bex.berachain.com/',
        'sec-ch-ua': '',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-site',
        'user-agent': '',
    },
    tap: {
        authority: 'artio-80085-faucet-api-recaptcha.berachain.com',
        accept: '*/*',
        'accept-language': '',
        authorization: '',
        origin: 'https://artio.faucet.berachain.com',
        referer: 'https://artio.faucet.berachain.com/',
        'sec-ch-ua': '',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-site',
        'user-agent': '',
    },
};

export type RequestTypes = 'galxe' | 'route' | 'tap';
